# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created: Thu Nov 26 22:56:47 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(852, 673)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 851, 641))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.lineEditMarketValueSH = QtGui.QLineEdit(self.tab)
        self.lineEditMarketValueSH.setGeometry(QtCore.QRect(550, 50, 121, 31))
        self.lineEditMarketValueSH.setObjectName(_fromUtf8("lineEditMarketValueSH"))
        self.btnCalGDP = QtGui.QPushButton(self.tab)
        self.btnCalGDP.setGeometry(QtCore.QRect(740, 70, 75, 31))
        self.btnCalGDP.setObjectName(_fromUtf8("btnCalGDP"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(490, 60, 54, 12))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(490, 100, 54, 12))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEditMarketValueSZ = QtGui.QLineEdit(self.tab)
        self.lineEditMarketValueSZ.setGeometry(QtCore.QRect(550, 90, 121, 31))
        self.lineEditMarketValueSZ.setObjectName(_fromUtf8("lineEditMarketValueSZ"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(680, 60, 54, 12))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(680, 100, 54, 12))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.btnTradeInfor = QtGui.QPushButton(self.tab)
        self.btnTradeInfor.setGeometry(QtCore.QRect(20, 50, 101, 31))
        self.btnTradeInfor.setObjectName(_fromUtf8("btnTradeInfor"))
        self.btnMarketAna = QtGui.QPushButton(self.tab)
        self.btnMarketAna.setGeometry(QtCore.QRect(130, 50, 101, 31))
        self.btnMarketAna.setObjectName(_fromUtf8("btnMarketAna"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(460, 30, 361, 101))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.lineEditDateRec = QtGui.QLineEdit(self.tab_6)
        self.lineEditDateRec.setGeometry(QtCore.QRect(40, 70, 121, 21))
        self.lineEditDateRec.setObjectName(_fromUtf8("lineEditDateRec"))
        self.btnPatternRecAna = QtGui.QPushButton(self.tab_6)
        self.btnPatternRecAna.setGeometry(QtCore.QRect(170, 63, 75, 31))
        self.btnPatternRecAna.setObjectName(_fromUtf8("btnPatternRecAna"))
        self.label = QtGui.QLabel(self.tab_6)
        self.label.setGeometry(QtCore.QRect(40, 160, 131, 41))
        self.label.setObjectName(_fromUtf8("label"))
        self.listWidgetMatchDate = QtGui.QListWidget(self.tab_6)
        self.listWidgetMatchDate.setGeometry(QtCore.QRect(40, 210, 256, 291))
        self.listWidgetMatchDate.setObjectName(_fromUtf8("listWidgetMatchDate"))
        self.pButtonSelect = QtGui.QPushButton(self.tab_6)
        self.pButtonSelect.setGeometry(QtCore.QRect(310, 220, 71, 31))
        self.pButtonSelect.setObjectName(_fromUtf8("pButtonSelect"))
        self.comboBoxStockID = QtGui.QComboBox(self.tab_6)
        self.comboBoxStockID.setGeometry(QtCore.QRect(160, 160, 131, 31))
        self.comboBoxStockID.setObjectName(_fromUtf8("comboBoxStockID"))
        self.label_6 = QtGui.QLabel(self.tab_6)
        self.label_6.setGeometry(QtCore.QRect(40, 30, 201, 41))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.btnMarketMoodAna_2 = QtGui.QPushButton(self.tab_2)
        self.btnMarketMoodAna_2.setGeometry(QtCore.QRect(60, 40, 101, 31))
        self.btnMarketMoodAna_2.setObjectName(_fromUtf8("btnMarketMoodAna_2"))
        self.btnMarketMoodAna_3 = QtGui.QPushButton(self.tab_2)
        self.btnMarketMoodAna_3.setGeometry(QtCore.QRect(190, 40, 101, 31))
        self.btnMarketMoodAna_3.setObjectName(_fromUtf8("btnMarketMoodAna_3"))
        self.btnMarketMoodAna_7 = QtGui.QPushButton(self.tab_2)
        self.btnMarketMoodAna_7.setGeometry(QtCore.QRect(320, 40, 101, 31))
        self.btnMarketMoodAna_7.setObjectName(_fromUtf8("btnMarketMoodAna_7"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.btnPatternRecAna_2 = QtGui.QPushButton(self.tab_4)
        self.btnPatternRecAna_2.setGeometry(QtCore.QRect(260, 50, 111, 31))
        self.btnPatternRecAna_2.setObjectName(_fromUtf8("btnPatternRecAna_2"))
        self.lineEditStockID_2 = QtGui.QLineEdit(self.tab_4)
        self.lineEditStockID_2.setGeometry(QtCore.QRect(120, 50, 121, 31))
        self.lineEditStockID_2.setObjectName(_fromUtf8("lineEditStockID_2"))
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 131, 41))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.btnMarketMoodAna_4 = QtGui.QPushButton(self.tab_7)
        self.btnMarketMoodAna_4.setGeometry(QtCore.QRect(70, 40, 101, 31))
        self.btnMarketMoodAna_4.setObjectName(_fromUtf8("btnMarketMoodAna_4"))
        self.btnMarketMoodAna_5 = QtGui.QPushButton(self.tab_7)
        self.btnMarketMoodAna_5.setGeometry(QtCore.QRect(200, 40, 101, 31))
        self.btnMarketMoodAna_5.setObjectName(_fromUtf8("btnMarketMoodAna_5"))
        self.btnMarketMoodAna_6 = QtGui.QPushButton(self.tab_7)
        self.btnMarketMoodAna_6.setGeometry(QtCore.QRect(330, 40, 101, 31))
        self.btnMarketMoodAna_6.setObjectName(_fromUtf8("btnMarketMoodAna_6"))
        self.btnMarketMoodAna_8 = QtGui.QPushButton(self.tab_7)
        self.btnMarketMoodAna_8.setGeometry(QtCore.QRect(460, 40, 101, 31))
        self.btnMarketMoodAna_8.setObjectName(_fromUtf8("btnMarketMoodAna_8"))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.btnMarketMoodAna_9 = QtGui.QPushButton(self.tab_5)
        self.btnMarketMoodAna_9.setGeometry(QtCore.QRect(60, 50, 101, 31))
        self.btnMarketMoodAna_9.setObjectName(_fromUtf8("btnMarketMoodAna_9"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.btnPatternRecAna, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditDateRec.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "基于模式识别的stock交易系统", None))
        self.lineEditMarketValueSH.setText(_translate("MainWindow", "29.99", None))
        self.btnCalGDP.setText(_translate("MainWindow", "计算", None))
        self.label_2.setText(_translate("MainWindow", "上证市值", None))
        self.label_3.setText(_translate("MainWindow", "深证市值", None))
        self.lineEditMarketValueSZ.setText(_translate("MainWindow", "22.65", None))
        self.label_4.setText(_translate("MainWindow", "万亿元", None))
        self.label_5.setText(_translate("MainWindow", "万亿元", None))
        self.btnTradeInfor.setText(_translate("MainWindow", "交易提示", None))
        self.btnMarketAna.setText(_translate("MainWindow", "市场分析", None))
        self.groupBox.setTitle(_translate("MainWindow", "GDP计算", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "每日提醒", None))
        self.btnPatternRecAna.setText(_translate("MainWindow", "模式识别", None))
        self.label.setText(_translate("MainWindow", "请选择查看股票代码", None))
        self.pButtonSelect.setText(_translate("MainWindow", "选择", None))
        self.label_6.setText(_translate("MainWindow", "请输入交易日（2008/08/08）", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "模式识别", None))
        self.btnMarketMoodAna_2.setText(_translate("MainWindow", "时间周期分析", None))
        self.btnMarketMoodAna_3.setText(_translate("MainWindow", "空间周期分析", None))
        self.btnMarketMoodAna_7.setText(_translate("MainWindow", "退出原则", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "风险控制", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "仓位管理", None))
        self.btnPatternRecAna_2.setText(_translate("MainWindow", "量化交易计算", None))
        self.label_7.setText(_translate("MainWindow", "请输入交易代码：", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "量化交易", None))
        self.btnMarketMoodAna_4.setText(_translate("MainWindow", "行业前景", None))
        self.btnMarketMoodAna_5.setText(_translate("MainWindow", "财务状况", None))
        self.btnMarketMoodAna_6.setText(_translate("MainWindow", "管理团队", None))
        self.btnMarketMoodAna_8.setText(_translate("MainWindow", "股票个性", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "选票系统", None))
        self.btnMarketMoodAna_9.setText(_translate("MainWindow", "欧洲市场", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "信息获取", None))
        self.menu.setTitle(_translate("MainWindow", "系统", None))
        self.menu_2.setTitle(_translate("MainWindow", "帮助", None))

